server:
  # 指定端口在40001
  port: 40001
  servlet:
    context-path: /wechat/manager

spring:
  application:
    name: wechat-server
management:
  endpoints:
    web:
      exposure:
        include: '*'

weixin:
  base-url: https://api.weixin.qq.com/cgi-bin
