server:
  # 指定端口在40001
  port: 40001
  servlet:
    context-path: /wechat/manager

spring:
  application:
    name: wechat-server
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/wechat_manager?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: net.sf.log4jdbc.DriverSpy
    maximum-pool-size: 100
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

weixin:
  base-url: https://api.weixin.qq.com/cgi-bin
